"""推荐知识库与主题库数据（纯数据）"""


# ── 内置推荐知识库（知识库目录生成后替换为文件查询）────

RECOMMENDATION_POOL = [
    # ── Lv.1 新手 ──
    {
        "id": "cup",
        "title": "画一个杯子 🥤",
        "summary": "从最简单的圆柱体开始练习",
        "description": "杯子是圆柱体 + 弧线把手的组合，是学画最经典的起步练习。先画杯口椭圆（长轴和短轴决定视角），再画杯身垂直线，最后加把手。",
        "min_level": 1, "max_level": 2,
        "interests": ["*", "daily", "food"],
        "master": "莫兰迪",
        "master_work": "静物（瓶罐系列）",
        "learn_point": "看莫兰迪怎么用最少的形状变化画出丰富的画面——你画杯子不需要细节，形状对了就成功了一半",
        "difficulty": 1,
    },
    {
        "id": "apple",
        "title": "画一个苹果 🍎",
        "summary": "第一次给物体加上明暗",
        "description": "找一个有侧面光源的苹果，画出五大调子——亮面、灰面、明暗交界线、反光、投影。明暗交界线是最暗的，反光比投影亮一点。",
        "min_level": 1, "max_level": 2,
        "interests": ["*", "daily"],
        "master": "塞尚",
        "master_work": "《静物苹果篮子》",
        "learn_point": "塞尚的苹果不是画「红色的圆」——他用冷暖色块的交界来表现苹果的立体感，而不是用明暗渐变",
        "difficulty": 1,
    },
    {
        "id": "tree",
        "title": "画一棵树 🌳",
        "summary": "练习用简单形状概括复杂自然物",
        "description": "树干是圆柱，树冠是大球体/锥体。先画基本形状，再往里分叉和加小细节。不要一上来画每片叶子——先抓整体。",
        "min_level": 1, "max_level": 2,
        "interests": ["flower"],
        "master": "门采尔",
        "master_work": "风景速写",
        "learn_point": "门采尔的树不是画叶子——他画的是树冠的剪影形状和树干的空间姿态",
        "difficulty": 1,
    },
    {
        "id": "hand",
        "title": "画自己的手 🖐️",
        "summary": "练习观察轮廓和比例",
        "description": "把手放在纸上，先看整体剪影——不要一根根画手指，先画整体形状再加手指分界线。注意手指之间的缝隙（负形）。",
        "min_level": 1, "max_level": 2,
        "interests": ["portrait"],
        "master": "荷尔拜因",
        "master_work": "肖像手部习作",
        "learn_point": "荷尔拜因画手的时候也是先定手腕和手掌的大形状——手指的细节不是在轮廓上添加的，而是在大形里切分出来的",
        "difficulty": 1,
    },
    {
        "id": "silhouette",
        "title": "窗外风景剪影 🪟",
        "summary": "剪影观察法练习",
        "description": "看窗外，把所有东西想象成纯黑剪影。只画外轮廓——建筑、树、电线杆的剪影。如果轮廓对了，画面就成功了 80%。",
        "min_level": 1, "max_level": 2,
        "interests": ["flower"],
        "master": "霍克尼",
        "master_work": "风景速写系列",
        "learn_point": "霍克尼用最简洁的形状概括复杂的风景——先看大色块，再看细节",
        "difficulty": 1,
    },
    # ── Lv.2-Lv.3 基础→进阶 ──
    {
        "id": "sphere",
        "title": "画一个球（完整五大调子）⚪",
        "summary": "精确练习五大调子",
        "description": "找一个球（篮球/苹果/橘子），放在台灯下。五大调子中，明暗交界线是最暗的弧线——它跟着球的弧度走，不是随意的一条线。",
        "min_level": 2, "max_level": 3,
        "interests": ["*"],
        "master": "伦勃朗",
        "master_work": "《自画像》系列",
        "learn_point": "看伦勃朗怎么用光的包络面来塑造立体感——他的脸不是一条条线画出来的，是一个个面的转折",
        "difficulty": 2,
    },
    {
        "id": "eye",
        "title": "画自己的眼睛 👁️",
        "summary": "人脸局部——培养观察精度",
        "description": "对着镜子画自己一只眼睛。记住：眼睛是球体嵌在眼窝里，不是平的。上眼睑有厚度（会受光），虹膜有放射状纹理。",
        "min_level": 2, "max_level": 3,
        "interests": ["portrait"],
        "master": "达芬奇",
        "master_work": "《蒙娜丽莎》局部",
        "learn_point": "达芬奇画眼睛时，眼角的阴影不是黑色——是最深的暖棕色，和周围的肤色有微妙过渡",
        "difficulty": 2,
    },
    {
        "id": "perspective",
        "title": "画一个房间角落 🏠",
        "summary": "一点透视练习",
        "description": "坐在房间角落，画你看到的墙线。注意：所有向远方延伸的线都汇聚到一个消失点。加上门、窗、家具的简化形状。",
        "min_level": 2, "max_level": 3,
        "interests": ["flower"],
        "master": "维米尔",
        "master_work": "《倒牛奶的女仆》",
        "learn_point": "维米尔画室内空间时，地砖的透视线是最明显的消失点指示——你看他画的地砖线是怎么指向同一个点的",
        "difficulty": 2,
    },
    {
        "id": "cat",
        "title": "画一只猫或狗 🐱",
        "summary": "动态线练习",
        "description": "动物不会乖乖站着，但照片可以。先找一张参考，找出脊椎的动态线——这是决定姿势是否生动的关键。动态线对了，身体其他部分往上「挂」。",
        "min_level": 2, "max_level": 3,
        "interests": ["animal"],
        "master": "德加",
        "master_work": "赛马系列",
        "learn_point": "德加画马奔跑时，背部的动态线是一条连贯的弧线——不是四个腿各管各的，而是整个身体有一个统一的动作趋势",
        "difficulty": 2,
    },
    {
        "id": "flower",
        "title": "画一朵花 🌸",
        "summary": "观察自然形态的细节",
        "description": "找一朵真花或照片。花瓣的排列有规律（螺旋/对称/放射），先看出规律再画。不要一瓣一瓣描——先画花蕊的中心位置，再围绕它画花瓣。",
        "min_level": 2, "max_level": 3,
        "interests": ["*", "flower"],
        "master": "梵高",
        "master_work": "《向日葵》",
        "learn_point": "梵高的向日葵每一朵花的朝向都不一样——他在安排构图时，让每朵花都「看向」不同的方向，画面就有了生命力",
        "difficulty": 2,
    },
    {
        "id": "still-life",
        "title": "画一瓶花（静物组合）💐",
        "summary": "第一次画多物体的组合",
        "description": "花瓶是圆柱体，花是球体/锥体。先画所有物体的大形状和位置关系（构图），再加明暗。注意花瓶和花的比例。",
        "min_level": 2, "max_level": 4,
        "interests": ["*"],
        "master": "塞尚",
        "master_work": "《静物苹果篮子》",
        "learn_point": "塞尚画静物时打破了单一视点——瓶口是俯视的、瓶身是平视的。他不是不会画透视，而是用不同的视点让画面更有「真实感」",
        "difficulty": 3,
    },
    # ── Lv.3-Lv.5 进阶→创作 ──
    {
        "id": "monet",
        "title": "临摹莫奈《日出·印象》🎨",
        "summary": "第一次临摹大师——学习用色",
        "description": "选莫奈的《日出·印象》，不求像，但求理解他的用色。注意：画中的颜色和你「以为」的颜色可能完全不一样。",
        "min_level": 3, "max_level": 5,
        "interests": ["*"],
        "master": "莫奈",
        "master_work": "《日出·印象》",
        "learn_point": "莫奈画日出时，太阳的橙色和水面的蓝色不是两个分开的颜色——它们互相映照，水面的蓝色里掺着橙色倒影",
        "difficulty": 3,
    },
    {
        "id": "portrait",
        "title": "画自己的正脸（肖像入门）👤",
        "summary": "第一次画完整的人脸",
        "description": "对着镜子画自己的正脸。三庭五眼：眼睛在头高的一半、鼻底在眼睛到下颏的一半、嘴在鼻子到下颏的一半。先画位置，再画细节。",
        "min_level": 3, "max_level": 4,
        "interests": ["portrait"],
        "master": "伦勃朗",
        "master_work": "自画像系列",
        "learn_point": "伦勃朗的自画像不是画五官——他是先画出光从哪里来，让光决定哪些部分亮、哪些在阴影里",
        "difficulty": 3,
    },
    {
        "id": "street",
        "title": "画一条街道（两点透视）🏛️",
        "summary": "练习两点透视",
        "description": "找有建筑的街道照片。左右两排建筑的线分别消失于两个消失点。加上行人（简化）、路灯、路牌。",
        "min_level": 3, "max_level": 4,
        "interests": ["flower"],
        "master": "萨金特",
        "master_work": "威尼斯街景系列",
        "learn_point": "萨金特画街景时，建筑的透视线巧妙地引导目光穿过画面——透视不只是「画准」，而是引导观众的视线走向",
        "difficulty": 3,
    },
    {
        "id": "van-gogh",
        "title": "临摹梵高《星夜》🌌",
        "summary": "学习笔触的表现力",
        "description": "选梵高的《星夜》或《向日葵》，重点观察他的笔触方向和长短。他不是涂色——每一笔都有方向、有力量。",
        "min_level": 3, "max_level": 5,
        "interests": ["*"],
        "master": "梵高",
        "master_work": "《星夜》",
        "learn_point": "梵高的《星夜》里，天空的笔触不是随机旋转的——它们沿着一个大的漩涡方向走，让整片天空在动",
        "difficulty": 3,
    },
    {
        "id": "figure",
        "title": "画一个路人（户外速写）🚶",
        "summary": "真实世界中的人",
        "description": "去咖啡馆或坐在窗边画路人。人会动所以必须快速捕捉——先画动态线和大形状，人走了凭记忆补细节。",
        "min_level": 3, "max_level": 5,
        "interests": ["portrait"],
        "master": "门采尔",
        "master_work": "生活速写集",
        "learn_point": "门采尔画人在街上走路时，经常只画了动态线和外轮廓——因为人已经走过去了，但他抓住了最核心的姿态",
        "difficulty": 3,
    },
    {
        "id": "schiele",
        "title": "临摹席勒自画像 🎭",
        "summary": "学习线条的情绪和张力",
        "description": "选席勒的一幅自画像，模仿他「紧张而扭曲」的线条。用线条表达情绪——你的线条是紧张的还是放松的？不是画得像，是画得有感觉。",
        "min_level": 4, "max_level": 5,
        "interests": ["portrait"],
        "master": "席勒",
        "master_work": "自画像",
        "learn_point": "席勒的线条为什么有张力？因为他不是画「身体的轮廓」——他在画「身体在空间中的边界感」，线条是断的、扭的，但位置准确",
        "difficulty": 4,
    },
    {
        "id": "morandi",
        "title": "像莫兰迪一样画静物 🏺",
        "summary": "低饱和度配色的魅力",
        "description": "找几个瓶瓶罐罐摆一组静物。尝试用低饱和度的灰色调来画——每个颜色里都掺一点灰，画面就会「安静」下来。",
        "min_level": 4, "max_level": 5,
        "interests": ["*"],
        "master": "莫兰迪",
        "master_work": "静物系列",
        "learn_point": "莫兰迪的颜色之所以高级，不是因为颜色本身——是因为每个颜色的明度（亮度）控制得刚刚好，瓶子和背景的明度差很小",
        "difficulty": 4,
    },
    {
        "id": "free-create",
        "title": "自由创作日 🎨",
        "summary": "画任何你想画的东西",
        "description": "今天没有规则。画你想画的任何东西——一幅完整的画、一张速写、甚至是涂鸦。画了就算赢，享受画画本身。",
        "min_level": 1, "max_level": 5,
        "interests": ["*"],
        "master": "",
        "master_work": "",
        "learn_point": "今天不做比较。你画出的每一笔，都是昨天之前的你做不到的。留住这张画，下周再看。",
        "difficulty": 1,
    },
]

MAX_VISIBLE_LEVEL = 5


# ── 主题库（按难度分级）──────────────────────────────────
# 供 /api/themes 与 /api/today-theme 使用，与 RECOMMENDATION_POOL 互补：
# RECOMMENDATION_POOL 偏「大师关联 + 长描述」，THEME_LIBRARY 偏「纯主题 + 难度筛选」。
THEME_LIBRARY = [
    # 入门 - 基础几何形状 + 日常物品（精简到 4 个）
    {"id": "cup", "title": "画一个杯子", "difficulty": "beginner", "category": "日常物品", "hint": "圆柱体加弧线把手", "icon": "☕"},
    {"id": "apple", "title": "画一个苹果", "difficulty": "beginner", "category": "日常物品", "hint": "球体加凹陷的顶部", "icon": "🍎"},
    {"id": "ball", "title": "画一个球", "difficulty": "beginner", "category": "几何形体", "hint": "圆形加明暗过渡", "icon": "⚪"},
    {"id": "leaf", "title": "画一片树叶", "difficulty": "beginner", "category": "自然", "hint": "叶脉的对称线条", "icon": "🍃"},

    # 进阶 - 结构组合 + 自然形态（精简到 4 个）
    {"id": "hand", "title": "画一只手", "difficulty": "intermediate", "category": "人体", "hint": "手掌的几何概括和手指关节", "icon": "✋"},
    {"id": "chair", "title": "画一把椅子", "difficulty": "intermediate", "category": "家具", "hint": "透视和结构线", "icon": "🪑"},
    {"id": "flower", "title": "画一朵花", "difficulty": "intermediate", "category": "自然", "hint": "花瓣的层叠和旋转", "icon": "🌸"},
    {"id": "tree", "title": "画一棵树", "difficulty": "intermediate", "category": "自然", "hint": "树干结构和树冠体积", "icon": "🌳"},

    # 挑战 - 完整场景 + 人体（精简到 4 个）
    {"id": "building", "title": "画一栋建筑", "difficulty": "advanced", "category": "建筑", "hint": "两点透视和细节取舍", "icon": "🏠"},
    {"id": "portrait", "title": "画一张人脸", "difficulty": "advanced", "category": "人体", "hint": "三庭五眼比例", "icon": "👤"},
    {"id": "landscape", "title": "画一处风景", "difficulty": "advanced", "category": "风景", "hint": "近中远三景层次", "icon": "🏞️"},
    {"id": "animal", "title": "画一只动物", "difficulty": "advanced", "category": "动物", "hint": "骨骼结构和毛发质感", "icon": "🐱"},
]

# 难度 → 中文标签
DIFFICULTY_LABELS = {
    "beginner": "入门",
    "intermediate": "进阶",
    "advanced": "挑战",
}
